services:
  lecturizeit-proxy:
    image: nginx:1.27.1-alpine
    ports:
      - "80:80"
    networks:
      - lecturizeit-network
    depends_on:
      - lecturizeit-api
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf