services:
  lecturizeit-proxy:
    image: nginx:1.27.1-alpine
    ports:
      - "80:80"
      - "443:443"
    networks:
      - lecturizeit-network
    depends_on:
      - lecturizeit-api
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem